-- SQLite
drop table CARD_DATA;
drop table TRX_INFO;
drop table ENCDEC_INFO;

-- SQLite
create table CARD_DATA (
MGNT_ID CHAR(20) NOT NULL,
CARD_NO int NOT NULL,
MONTHLY_PAY INT  NOT NULL,
AVL_END_YMD CHAR(4)  NOT NULL ,
CVC INT  NOT NULL,
TRNS_AMT int,
VAT int,
CANCL_AMT int,
CANCL_VAT int,
TRNS_MGNT_NO CHAR(20),
PASSWORD_CARD_INFO VARCHAR2(300),
ADD_FIELD VARCHAR2(47),
TRT_STS VARCHAR2(10),
EMP_NO VARCHAR2(10),
DATA_REG_TM TIMESTAMP,
DATA_UPD_TM TIMESTAMP,
PRIMARY KEY (MGNT_ID, CARD_NO, MONTHLY_PAY, AVL_END_YMD, CVC)
)

;
create table ENCDEC_INFO (
ENCRYPT VARCHAR2(300) ,
KEY_DAT    VARCHAR2(300) 
)

;
create table TRX_INFO (
TRX_ID CHAR(20) ,
HEADER CHAR(34) ,
DATA CHAR(416) ,
DATA_REG_TM TIMESTAMP
)